// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg-V27TPo8qBs2UFxchsUkt0Hjiqdx2J0',
    appId: '1:625829856237:web:916992db024aed6a829de4',
    messagingSenderId: '625829856237',
    projectId: 'goal-mate-85b8c',
    authDomain: 'goal-mate-85b8c.firebaseapp.com',
    storageBucket: 'goal-mate-85b8c.appspot.com',
    measurementId: 'G-YMKDRQE97L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-OfWZcReA-cZQQu8EA9y4BOs1yOAXEeA',
    appId: '1:625829856237:android:7592948997f8c7fb829de4',
    messagingSenderId: '625829856237',
    projectId: 'goal-mate-85b8c',
    storageBucket: 'goal-mate-85b8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtAnTBgLT4oLgHBLgWcejJLMzulKm6BfE',
    appId: '1:625829856237:ios:e851c6766df0976c829de4',
    messagingSenderId: '625829856237',
    projectId: 'goal-mate-85b8c',
    storageBucket: 'goal-mate-85b8c.appspot.com',
    iosBundleId: 'com.example.goalmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtAnTBgLT4oLgHBLgWcejJLMzulKm6BfE',
    appId: '1:625829856237:ios:eaea49dcb1ae8809829de4',
    messagingSenderId: '625829856237',
    projectId: 'goal-mate-85b8c',
    storageBucket: 'goal-mate-85b8c.appspot.com',
    iosBundleId: 'com.example.goalmate.RunnerTests',
  );
}
